### ISSUE TITLE
Parametrar att använda i URL för deleted files?

### ISSUE THREAD

**Issue by hanspalsson** [libris/export#3]
Hej! I URL:en som används i export_nix.sh för att hämta data från Libris via API finns två parametrar som är odokumenterade;
deleted=ignore&virtualDelete=false

true/false är lätt att gissa sig till men ignore? Vad är betydelsen av parametrarna och vad är dess värden? För den som inte vill ha med raderade poster i exporten är det nyttig info.

Tack! /Hans

**Comment by maiadexander** [comment]
Hej!
För frågor om Libris dataflöden, vänligen besök kb.se/libris eller Supportforum för nya Libris. 

Hälsar vänligt, 
Maia Dexander
Avdelningen för informationssystem
Kungliga biblioteket
070-007 36 52
maia.dexander@kb.se

**Comment by kaipoykio** [comment]
Dessa parametrar behöver ej anges om man inte vill ha med raderade poster.

Men annars:

deleted = ignore(default), export, email (från exportprofilen)

virtualDelete = false(default), true (// Virtual deletion means: If there exists no holding for any of the locations in the profile for a bib record, consider that bib record deleted.)

mvh,
Kai
